NanoMQ_CLI(dds/someip/zeromq) supports to run http server
emqx/nanomq pull request #1027
Opened 2023-02-02 06:46 UTC by alvin1221

2023-02-02 06:51 UTC, lee-emqx approved these changes

2023-02-02 06:53 UTC, alvin1221 commented
Base on https://github.com/nanomq/NanoNNG/pull/421

2023-02-02 09:22 UTC, JaylinYu requested changes
build failed

2023-02-02 10:29 UTC, alvin1221 commented
> nanomq/NanoNNG#421

require https://github.com/nanomq/NanoNNG/pull/421

2023-02-03 10:37 UTC, JaylinYu approved these changes

2023-02-03 10:37 UTC, merged