* NEW [fuzzy test] add fuzzy test in workflow.
emqx/nanomq pull request #1063
Opened 2023-02-16 09:34 UTC by Hermann0222

2023-02-16 10:23 UTC, Hermann0222 commented on .github/scripts/fuzzy_test.py
> +    with open('../.github/scripts/fuzzy_test.txt', 'r') as f:
I'm not sure whether it is appropriate to use relative path.

2023-02-16 13:09 UTC, JaylinYu commented
well done bro!

2023-02-17 03:12 UTC, wanghaEMQ requested changes
Make it configurable and readable

2023-02-17 05:29 UTC, wanghaEMQ approved these changes

2023-02-17 05:49 UTC, wanghaEMQ approved these changes

2023-02-17 05:49 UTC, merged