Fix the wrong number of bridge_aios for sending.
emqx/nanomq pull request #1188
Opened 2023-04-20 06:59 UTC by wanghaEMQ

* Fix the wrong number of bridge_aios for sending.
* Add a comment to web_server.c about a process with low performance.
* Reduce one shot of calculating in length.

2023-04-20 09:08 UTC, JaylinYu commented
Plz double check! it doesnt work!

2023-04-20 09:08 UTC, JaylinYu requested changes
plz refer to my previous PR

2023-04-21 10:38 UTC, wanghaEMQ commented on nanomq/bridge.c
> +	for (uint32_t num = 0; num < config->parallel; num++) {
Sorry. The change was removed.

2023-04-22 10:59 UTC, JaylinYu approved these changes
This is a good start

2023-04-23 03:30 UTC, Hermann0222 approved these changes

2023-04-23 12:04 UTC, Hermann0222 approved these changes

2023-04-23 14:45 UTC, merged

2023-04-30 02:46 UTC, JaylinYu reviewed
I have to revert this first

2023-04-30 02:46 UTC, JaylinYu commented on nanomq/web_server.c
> +		// TODO performace bottlenect here (Copy structure 3 times)
nevermind, webserver is not meant to be performant