Adapt to bridge changes from NNG
emqx/nanomq pull request #1219
Opened 2023-05-04 07:50 UTC by alvin1221

Please merge https://github.com/nanomq/NanoNNG/pull/549 first .

2023-05-04 09:22 UTC, wanghaEMQ approved these changes

2023-05-05 01:49 UTC, lee-emqx approved these changes

2023-05-05 08:25 UTC, JaylinYu requested changes
now move head and run CI

2023-05-06 10:54 UTC, JaylinYu approved these changes
rerun ci in next pr

2023-05-06 10:54 UTC, JaylinYu approved these changes
rerun ci in next pr

2023-05-06 10:54 UTC, merged