Refactor post_rules.
emqx/nanomq pull request #1385
Opened 2023-07-18 03:09 UTC by lee-emqx

2023-07-18 10:54 UTC, wanghaEMQ approved these changes

2023-07-18 12:12 UTC, RanMaoyi approved these changes
LGTM

2023-07-19 05:57 UTC, JaylinYu commented
why does everything failed?

2023-07-19 05:58 UTC, JaylinYu requested changes
plz check CI,

2023-07-19 09:44 UTC, merged