Update the documentation for the gateway related to HTTP API.
emqx/nanomq pull request #1389
Opened 2023-07-20 02:23 UTC by lee-emqx

2023-07-20 03:49 UTC, wanghaEMQ requested changes

2023-07-20 03:49 UTC, wanghaEMQ commented on docs/en_US/gateway/dds.md
> +    # #
Duplicated description
```
    # # Basic authorization
    # #
```

2023-07-20 03:49 UTC, wanghaEMQ commented on docs/en_US/gateway/dds.md
> +- 重启网关：
Typo

2023-07-20 03:49 UTC, wanghaEMQ commented on docs/en_US/gateway/dds.md
> +$ curl --basic -u admin:public 'http://127.0.0.1:8082/api/v4/proxy/ctrl/stop' \
stop?

2023-07-20 03:49 UTC, wanghaEMQ commented on docs/en_US/gateway/someip-gateway.md
> +    # #
Duplicated description

2023-07-20 06:45 UTC, lee-emqx commented on docs/en_US/gateway/dds.md
> +$ curl --basic -u admin:public 'http://127.0.0.1:8082/api/v4/proxy/ctrl/stop' \
Yes, it's.

2023-07-20 06:45 UTC, lee-emqx commented on docs/en_US/gateway/dds.md
> +- 重启网关：
Thank you, the issue has been resolved!

2023-07-21 02:22 UTC, LenaLenaPan approved these changes

2023-07-21 03:49 UTC, wanghaEMQ approved these changes

2023-07-21 03:49 UTC, merged