aws bridge test & docs fix
emqx/nanomq pull request #1478
Opened 2023-10-08 07:04 UTC by OdyWayne

2023-10-08 07:12 UTC, RanMaoyi approved these changes
good!

2023-10-08 07:50 UTC, OdyWayne commented
should merge --> https://github.com/nanomq/NanoNNG/pull/705 first

2023-10-08 08:35 UTC, lee-emqx approved these changes

2023-10-08 11:13 UTC, wanghaEMQ reviewed
Is it safe to make those keys public?

2023-10-08 13:55 UTC, JaylinYu requested changes
plz remove the pem/key

2023-10-08 15:21 UTC, OdyWayne commented
> plz remove the pem/key

Without those, then CI for aws bridge test is impossible. We may need further discussion.

2023-10-09 03:17 UTC, JaylinYu approved these changes

2023-10-09 03:19 UTC, JaylinYu commented
gonna merge it first.
need to have a limited aws iot core service

2023-10-09 03:19 UTC, merged