Update docs http-api.md
emqx/nanomq pull request #649
Opened 2022-06-09 03:10 UTC by alvin1221

2022-06-09 06:24 UTC, JaylinYu approved these changes

2022-06-09 06:25 UTC, JaylinYu commented
please reserve old version of API Doc

2022-06-09 06:26 UTC, JaylinYu requested changes
please submit a new MD file as new ver of API Doc

2022-06-10 10:00 UTC, JaylinYu approved these changes

2022-06-10 10:01 UTC, lee-emqx approved these changes

2022-06-10 10:02 UTC, wanghaEMQ approved these changes

2022-06-10 10:17 UTC, merged