Update conf for congestion control algorithm
emqx/nanomq pull request #875
Opened 2022-10-24 10:10 UTC by lee-emqx

2022-10-24 10:32 UTC, wanghaEMQ approved these changes

2022-10-25 10:48 UTC, JaylinYu approved these changes

2022-10-27 04:07 UTC, JaylinYu requested changes
need to switch back to original conf file

2022-10-27 04:07 UTC, JaylinYu commented on CMakeLists.txt
> +  add_definitions(-DQUIC_API_ENABLE_PREVIEW_FEATURES)
what is this for?

2022-10-27 04:07 UTC, JaylinYu commented on etc/nanomq.conf
> +			address="mqtt-tcp://localhost:1883"
better not

2022-10-27 05:57 UTC, JaylinYu commented
sorry I have to close this due to merging difficulities

2022-10-27 08:15 UTC, closed without merging