Add `ACL` configuration file
emqx/nanomq pull request #879
Opened 2022-10-27 02:10 UTC by alvin1221

2022-10-28 09:42 UTC, JaylinYu requested changes
plz merge into nanomq.conf
and erlang tuple format is not mandotary

2022-10-31 10:25 UTC, alvin1221 commented
> 

Done

2022-10-31 14:09 UTC, JaylinYu approved these changes

2022-11-01 02:10 UTC, lee-emqx approved these changes

2022-11-01 03:01 UTC, JaylinYu approved these changes

2022-11-01 03:01 UTC, merged